micronaut:
  application:
    name: vitalizr-web
    jackson:
      indentOutput: true
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://nicholasvaidyanathan.me